// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBoBFM0U7BkvdxZpxC1iBqfQ1y6Im8zr4',
    appId: '1:557968649545:web:fa665844fe9cdc4849fe98',
    messagingSenderId: '557968649545',
    projectId: 'totalx-d1900',
    authDomain: 'totalx-d1900.firebaseapp.com',
    storageBucket: 'totalx-d1900.appspot.com',
    measurementId: 'G-G68VZLZMLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboyc4CCp8wLBpahjz8pEsCGeTBpZw9Nw',
    appId: '1:557968649545:android:090d99ec8d1549e449fe98',
    messagingSenderId: '557968649545',
    projectId: 'totalx-d1900',
    storageBucket: 'totalx-d1900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTP8JJnjTb-DCa1T2OHTuzGl7jSxJk2vk',
    appId: '1:557968649545:ios:b17bfec0108f329949fe98',
    messagingSenderId: '557968649545',
    projectId: 'totalx-d1900',
    storageBucket: 'totalx-d1900.appspot.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTP8JJnjTb-DCa1T2OHTuzGl7jSxJk2vk',
    appId: '1:557968649545:ios:b17bfec0108f329949fe98',
    messagingSenderId: '557968649545',
    projectId: 'totalx-d1900',
    storageBucket: 'totalx-d1900.appspot.com',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBoBFM0U7BkvdxZpxC1iBqfQ1y6Im8zr4',
    appId: '1:557968649545:web:08a5f8a36ae623db49fe98',
    messagingSenderId: '557968649545',
    projectId: 'totalx-d1900',
    authDomain: 'totalx-d1900.firebaseapp.com',
    storageBucket: 'totalx-d1900.appspot.com',
    measurementId: 'G-MCB0DYW5Q3',
  );
}
